parameters:
    markdown_cache_time: 86400

services:
    Psr\Cache\CacheItemPoolInterface $markdownCache: "@cache.markdown"
    Psr\Cache\CacheItemPoolInterface $rateLimitCache: "@cache.ratelimit"

framework:
    cache:
        pools:
            cache.markdown:
                adapter: cache.app
                default_lifetime: "%markdown_cache_time%"
                public: true
            cache.ratelimit:
                adapter: cache.app
                public: true
