login:
    controller: App\Controller\SecurityController::login
    path: /login
    methods: [GET]

login_check:
    path: /login_check
    methods: [POST]

login_url:
    path: /login_url
    methods: [GET]

log_out:
    path: /log_out
