monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [302, 400, 403, 404, 405]
        nested:
            type: stream
            path: "%env(resolve:LOG_FILE)%"
            level: debug
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
