# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html

parameters:
    env(TRUSTED_HOSTS): ''
    submission_sort_modes: active|hot|new|top|controversial|most_commented
    number_regex: '[1-9][0-9]{0,17}'
    username_regex: '\w{3,25}|!deleted\d+'
    uuid_regex: '[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}'
    wiki_page_regex: '[A-Za-z][A-Za-z0-9_-]*(/[A-Za-z][A-Za-z0-9_-]*)*'

services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $appBranch: "%env(APP_BRANCH)%"
            $appVersion: "%env(APP_VERSION)%"
            $batchSize: "%env(BATCH_SIZE)%"
            $defaultLocale: "%env(APP_LOCALE)%"
            $fontsConfig: "%env(json:file:resolve:APP_FONTS)%"
            $themesConfig: "%env(json:file:resolve:APP_THEMES)%"
            $noReplyAddress: "%env(NO_REPLY_ADDRESS)%"
            $secret: "%env(APP_SECRET)%"
            $uploadRoot: "%env(resolve:UPLOAD_ROOT)%"
            bool $enableExperimentalRestApi: "%env(bool:ENABLE_EXPERIMENTAL_REST_API)%"
            bool $makeFirstUserAdmin: "%env(bool:MAKE_FIRST_USER_ADMIN)%"
            array $availableLocales: "%env(csv:AVAILABLE_LOCALES)%"
            array $ipWhitelist: "%env(csv:RATELIMIT_WHITELIST)%"
            array $trustedHosts: "%env(csv:TRUSTED_HOSTS)%"
        public: false

    _instanceof:
        App\Repository\Contracts\PrunesIpAddresses:
            tags: [postmill.ip_pruner]

        League\CommonMark\Inline\Parser\InlineParserInterface:
            tags: [commonmark.inline_parser]

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/{DependencyInjection,Entity,Migrations,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Command\PruneIpAddressesCommand:
        $pruners: !tagged postmill.ip_pruner

    App\Doctrine\Listener\DomainEventsListener:
        tags: ['doctrine.event_subscriber']

    App\Markdown\CommonMark\ImageWithFixedClassRenderer:
        tags:
            - { name: commonmark.inline_renderer, element: League\CommonMark\Inline\Element\Image, priority: 1 }

    App\Markdown\CommonMark\LanguageDetectionListener:
        tags:
            - { name: commonmark.event_listener, event: League\CommonMark\Event\DocumentParsedEvent }

    App\Markdown\CommonMark\SyntaxHighlightRenderer:
        tags:
            - { name: commonmark.block_renderer, element: League\CommonMark\Block\Element\FencedCode, priority: 1 }

    App\Markdown\Factory\EnvironmentFactory:
        $container: !service_locator
            League\CommonMark\ConfigurableEnvironmentInterface: '@League\CommonMark\ConfigurableEnvironmentInterface'

    App\Security\RateLimitExemptLimiter:
        stack:
            - App\Security\RateLimitExemptLimiter:
                  $ipWhitelist: "%env(csv:RATELIMIT_WHITELIST)%"
            - Symfony\Component\Security\Http\RateLimiter\DefaultLoginRateLimiter:
                  $globalFactory: "@limiter.login_global"
                  $localFactory: "@limiter.login_local"

    App\Storage\StorageInterface $imageStorage:
        class: App\Storage\FlysystemStorage
        arguments:
            $filesystem: "@postmill.submission_images"
